package com.caiocesarmods.caiocesarbiomes.World.worldgen.Climate;

public enum ClimateDomain {
    ICE_CAP,
    TUNDRA,
    SUBPOLAR_OCEANIC,
    SUBARTIC,
    TEMPERATE_CONTINENTAL,
    TEMPERATE_OCEANIC,
    TEMPERATE,
    TEMPERATE_HIGHLAND,
    TEMPERATE_CONTINENTAL_DESERT,
    TEMPERATE_DESERT,
    SUBTROPICAL_DESERT,
    SUBTROPICAL_OCEANIC_DESERT,
    TROPICAL_DESERT,
    TEMPERATE_CONTINENTAL_SEMIARID,
    TEMPERATE_SEMIARID,
    SUBTROPICAL_SEMIARID,
    SUBTROPICAL_OCEANIC_SEMIARID,
    TROPICAL_SEMIARID,
    SUBTROPICAL_MEDITERRANEAN,
    SUBTROPICAL_OCEANIC_MEDITERRANEAN,
    TEMPERATE_MEDITERRANEAN,
    TEMPERATE_OCEANIC_MEDITERRANEAN,
    TEMPERATE_CONTINENTAL_MEDITERRANEAN,
    HUMID_SUBTROPICAL,
    HUMID_SUBTROPICAL_HIGHLAND,
    HUMID_SUBTROPICAL_OCEANIC,
    TROPICAL_FOREST,
    TROPICAL_SAVANNA,
    OCEAN,
    LUKEWARM_OCEAN,
    WARM_OCEAN,
    COLD_OCEAN,
    ICY_OCEAN

}


